FROM maven:3.6.3-openjdk-14-slim

WORKDIR /app

# Prepare by downloading dependencies
ADD pom.xml /app/pom.xml
ADD src /app/src

ARG MODULE
CMD ["mvn", "clean", "test", "-DsuiteXmlFile=src/test/resources/suites/$MODULE"]



