version: "3"
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: selenoid
    network_mode: bridge
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "5", "-retry-count", "1000", "-session-attempt-timeout", "3m", "-service-startup-timeout", "3m"]
    ports:
      - 4444:4444
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config/:/etc/selenoid"
      - "$PWD/config/video:/opt/selenoid/video"
      - "$PWD/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/config/video"
      - TZ=Europe/Berlin
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.4.3"
    container_name: selenoid-ui
    network_mode: bridge
    command: -selenoid-uri 'http://selenoid:4444'
    ports:
      - 8080:8080
    links:
      - selenoid
  test-automation-template:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SUITE: regression-suite.xml
    container_name: test-automation-template
    network_mode: bridge
    volumes:
      - ${PWD}/target:/app/target
      - ${PWD}/logs:/app/logs
    links:
      - selenoid
  allure:
    image: "frankescobar/allure-docker-service:latest"
    container_name: allure
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: "TRUE"
      KEEP_HISTORY_LATEST: 10
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/target/allure-results:/app/allure-results
      - ${PWD}/target/allure-reports:/app/default-reports
